"""updating status of tasks and column name

Revision ID: 26e2e685a41c
Revises: 517b83e36811
Create Date: 2026-02-08 19:38:55.346801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26e2e685a41c'
down_revision: Union[str, Sequence[str], None] = '517b83e36811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the new column with correct name
    op.add_column('tasks', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    
    # Update existing rows: copy data from descritpion to description
    op.execute("UPDATE tasks SET description = descritpion")
    
    # Convert status from string to integer with explicit conversion
    # Map string values to integer values
    op.execute("""
        ALTER TABLE tasks 
        ALTER COLUMN status TYPE INTEGER 
        USING CASE status
            WHEN 'created' THEN 1
            WHEN 'in_progress' THEN 2
            WHEN 'done' THEN 3
            ELSE 1  -- Default to CREATED if unknown value
        END
    """)
    
    # Now drop the old column
    op.drop_column('tasks', 'descritpion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the old column with typo
    op.add_column('tasks', sa.Column('descritpion', sa.VARCHAR(), autoincrement=False, nullable=False))
    
    # Copy data back and convert integers to strings
    op.execute("UPDATE tasks SET descritpion = description")
    
    # Convert integer back to string
    op.execute("""
        ALTER TABLE tasks 
        ALTER COLUMN status TYPE VARCHAR 
        USING CASE status
            WHEN 1 THEN 'created'
            WHEN 2 THEN 'in_progress'
            WHEN 3 THEN 'done'
            ELSE 'created'
        END
    """)
    
    # Drop the correct column
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###